services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: gochat
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gochat
    ports:
      - "5432:5432"
    volumes:
      - gochat-db:/var/lib/postgresql

volumes:
  gochat-db:
